// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AppAiRun struct {
	ID                 pgtype.UUID        `json:"id"`
	ItemID             pgtype.UUID        `json:"item_id"`
	RevisionID         pgtype.UUID        `json:"revision_id"`
	Purpose            string             `json:"purpose"`
	ModelConfigID      pgtype.UUID        `json:"model_config_id"`
	PromptVersionID    pgtype.UUID        `json:"prompt_version_id"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	Background         bool               `json:"background"`
	State              string             `json:"state"`
	InputSha256        []byte             `json:"input_sha256"`
	ValidatedOutput    []byte             `json:"validated_output"`
	InputTokens        int64              `json:"input_tokens"`
	CachedInputTokens  int64              `json:"cached_input_tokens"`
	OutputTokens       int64              `json:"output_tokens"`
	ToolCalls          int32              `json:"tool_calls"`
	AttemptCount       int32              `json:"attempt_count"`
	EstimatedCostUsd   pgtype.Numeric     `json:"estimated_cost_usd"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	ClusterID          pgtype.UUID        `json:"cluster_id"`
}

type AppAiRunAttempt struct {
	ID                 int64              `json:"id"`
	AiRunID            pgtype.UUID        `json:"ai_run_id"`
	AttemptNumber      int32              `json:"attempt_number"`
	State              string             `json:"state"`
	ProviderResponseID pgtype.Text        `json:"provider_response_id"`
	InputTokens        int64              `json:"input_tokens"`
	CachedInputTokens  int64              `json:"cached_input_tokens"`
	OutputTokens       int64              `json:"output_tokens"`
	ReservedCostUsd    pgtype.Numeric     `json:"reserved_cost_usd"`
	EstimatedCostUsd   pgtype.Numeric     `json:"estimated_cost_usd"`
	BudgetSoftAlert    bool               `json:"budget_soft_alert"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ReservedToolCalls  int32              `json:"reserved_tool_calls"`
	ToolCalls          int32              `json:"tool_calls"`
}

type AppAnnotation struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	AnnotationType string             `json:"annotation_type"`
	StartOffset    pgtype.Int4        `json:"start_offset"`
	EndOffset      pgtype.Int4        `json:"end_offset"`
	QuoteHash      []byte             `json:"quote_hash"`
	Body           string             `json:"body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppAuditEvent struct {
	ID         int64              `json:"id"`
	ActorType  string             `json:"actor_type"`
	ActorID    string             `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   string             `json:"target_id"`
	RequestID  pgtype.Text        `json:"request_id"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppAuthAccount struct {
	ID                    pgtype.UUID        `json:"id"`
	Issuer                string             `json:"issuer"`
	AccountID             string             `json:"account_id"`
	ProviderID            string             `json:"provider_id"`
	UserID                pgtype.UUID        `json:"user_id"`
	AccessToken           pgtype.Text        `json:"access_token"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	IDToken               pgtype.Text        `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamptz `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text        `json:"scope"`
	Password              pgtype.Text        `json:"password"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AppAuthRateLimit struct {
	ID          pgtype.UUID `json:"id"`
	Key         string      `json:"key"`
	Count       int32       `json:"count"`
	LastRequest int64       `json:"last_request"`
}

type AppAuthSession struct {
	ID        pgtype.UUID        `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IpAddress pgtype.Text        `json:"ip_address"`
	UserAgent pgtype.Text        `json:"user_agent"`
	UserID    pgtype.UUID        `json:"user_id"`
}

type AppAuthVerification struct {
	ID         pgtype.UUID        `json:"id"`
	Identifier string             `json:"identifier"`
	Value      string             `json:"value"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AppClaim struct {
	ID                pgtype.UUID        `json:"id"`
	ItemID            pgtype.UUID        `json:"item_id"`
	RevisionID        pgtype.UUID        `json:"revision_id"`
	AiRunID           pgtype.UUID        `json:"ai_run_id"`
	ClaimIndex        int32              `json:"claim_index"`
	ClaimType         string             `json:"claim_type"`
	ClaimText         string             `json:"claim_text"`
	NormalizedValue   []byte             `json:"normalized_value"`
	Confidence        string             `json:"confidence"`
	Material          bool               `json:"material"`
	VerificationState string             `json:"verification_state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AppClusterMember struct {
	ClusterID  pgtype.UUID        `json:"cluster_id"`
	ItemID     pgtype.UUID        `json:"item_id"`
	Similarity pgtype.Numeric     `json:"similarity"`
	Method     string             `json:"method"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AppContentRevision struct {
	ID                      pgtype.UUID        `json:"id"`
	RawDocumentID           pgtype.UUID        `json:"raw_document_id"`
	PreviousRevisionID      pgtype.UUID        `json:"previous_revision_id"`
	NormalizedSha256        []byte             `json:"normalized_sha256"`
	NormalizedTextObjectKey string             `json:"normalized_text_object_key"`
	ParserName              string             `json:"parser_name"`
	ParserVersion           string             `json:"parser_version"`
	Title                   string             `json:"title"`
	Author                  string             `json:"author"`
	Language                string             `json:"language"`
	SourcePublishedAt       pgtype.Timestamptz `json:"source_published_at"`
	SourceUpdatedAt         pgtype.Timestamptz `json:"source_updated_at"`
	NormalizedBytes         int64              `json:"normalized_bytes"`
	Outline                 []byte             `json:"outline"`
	OffsetMap               []byte             `json:"offset_map"`
	Warnings                []byte             `json:"warnings"`
	ChangeKind              string             `json:"change_kind"`
	ChangeReason            string             `json:"change_reason"`
	MaterialChange          bool               `json:"material_change"`
	ObservedAt              pgtype.Timestamptz `json:"observed_at"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

type AppDedupeDecision struct {
	RevisionID      pgtype.UUID        `json:"revision_id"`
	ItemID          pgtype.UUID        `json:"item_id"`
	ClusterID       pgtype.UUID        `json:"cluster_id"`
	CandidateItemID pgtype.UUID        `json:"candidate_item_id"`
	Outcome         string             `json:"outcome"`
	Method          string             `json:"method"`
	Similarity      pgtype.Numeric     `json:"similarity"`
	SimhashDistance pgtype.Int4        `json:"simhash_distance"`
	Details         []byte             `json:"details"`
	EvaluatedAt     pgtype.Timestamptz `json:"evaluated_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppEmbedding struct {
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	RevisionID    pgtype.UUID        `json:"revision_id"`
	ModelID       string             `json:"model_id"`
	Dimensions    int32              `json:"dimensions"`
	Embedding     pgvector.Vector    `json:"embedding"`
	ContentSha256 []byte             `json:"content_sha256"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppEmbeddingModel struct {
	ModelID        string             `json:"model_id"`
	Provider       string             `json:"provider"`
	Dimensions     int32              `json:"dimensions"`
	LifecycleState string             `json:"lifecycle_state"`
	EvaluatedAt    pgtype.Timestamptz `json:"evaluated_at"`
	ActivatedAt    pgtype.Timestamptz `json:"activated_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppEvalCase struct {
	ID           pgtype.UUID        `json:"id"`
	Suite        string             `json:"suite"`
	InputFixture string             `json:"input_fixture"`
	Expected     []byte             `json:"expected"`
	Source       string             `json:"source"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AppEvalRun struct {
	ID              pgtype.UUID        `json:"id"`
	GitSha          string             `json:"git_sha"`
	ModelConfigID   pgtype.UUID        `json:"model_config_id"`
	PromptVersionID pgtype.UUID        `json:"prompt_version_id"`
	Metrics         []byte             `json:"metrics"`
	Result          string             `json:"result"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppEvidenceSpan struct {
	ID             pgtype.UUID        `json:"id"`
	ClaimID        pgtype.UUID        `json:"claim_id"`
	RevisionID     pgtype.UUID        `json:"revision_id"`
	SpanIdentifier string             `json:"span_identifier"`
	SectionPath    string             `json:"section_path"`
	StartOffset    int32              `json:"start_offset"`
	EndOffset      int32              `json:"end_offset"`
	QuoteHash      []byte             `json:"quote_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AppFeedback struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TargetType     string             `json:"target_type"`
	TargetID       pgtype.UUID        `json:"target_id"`
	FeedbackType   string             `json:"feedback_type"`
	Note           pgtype.Text        `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	MutationID     pgtype.UUID        `json:"mutation_id"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
}

type AppGithubRepository struct {
	SourceID        string             `json:"source_id"`
	NodeID          string             `json:"node_id"`
	RepositoryOwner string             `json:"repository_owner"`
	RepositoryName  string             `json:"repository_name"`
	EnabledEvents   []string           `json:"enabled_events"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AppInterestProfile struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Version        int64              `json:"version"`
	Name           string             `json:"name"`
	IsActive       bool               `json:"is_active"`
	ProfileSummary string             `json:"profile_summary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppInterestTopic struct {
	ProfileID  pgtype.UUID        `json:"profile_id"`
	TopicID    string             `json:"topic_id"`
	Priority   int16              `json:"priority"`
	Weight     pgtype.Numeric     `json:"weight"`
	Keywords   []string           `json:"keywords"`
	Exclusions []string           `json:"exclusions"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AppItem struct {
	ID                pgtype.UUID        `json:"id"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CanonicalUrl      string             `json:"canonical_url"`
	Title             string             `json:"title"`
	NormalizedTitle   string             `json:"normalized_title"`
	NormalizedAuthor  string             `json:"normalized_author"`
	PackageName       string             `json:"package_name"`
	Version           string             `json:"version"`
	Slug              string             `json:"slug"`
	LifecycleState    string             `json:"lifecycle_state"`
	EventType         string             `json:"event_type"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	FirstSeenAt       pgtype.Timestamptz `json:"first_seen_at"`
	Status            string             `json:"status"`
	Simhash           []byte             `json:"simhash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AppItemSource struct {
	RevisionID   pgtype.UUID        `json:"revision_id"`
	ItemID       pgtype.UUID        `json:"item_id"`
	CanonicalUrl string             `json:"canonical_url"`
	SourceRole   string             `json:"source_role"`
	SourceTier   string             `json:"source_tier"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AppItemStateMutation struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	MutationType   string             `json:"mutation_type"`
	BeforeState    []byte             `json:"before_state"`
	AfterState     []byte             `json:"after_state"`
	IdempotencyKey string             `json:"idempotency_key"`
	BulkID         pgtype.UUID        `json:"bulk_id"`
	UndoDeadline   pgtype.Timestamptz `json:"undo_deadline"`
	UndoneAt       pgtype.Timestamptz `json:"undone_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type AppItemTag struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ItemID    pgtype.UUID        `json:"item_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AppManualCapture struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	RequestedUrl   string             `json:"requested_url"`
	CanonicalUrl   string             `json:"canonical_url"`
	State          string             `json:"state"`
	SourceID       pgtype.Text        `json:"source_id"`
	EndpointID     pgtype.UUID        `json:"endpoint_id"`
	ItemID         pgtype.UUID        `json:"item_id"`
	ClusterID      pgtype.UUID        `json:"cluster_id"`
	ErrorCode      pgtype.Text        `json:"error_code"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppModelConfig struct {
	ID                       pgtype.UUID        `json:"id"`
	Role                     string             `json:"role"`
	Provider                 string             `json:"provider"`
	ModelID                  string             `json:"model_id"`
	Reasoning                string             `json:"reasoning"`
	Verbosity                string             `json:"verbosity"`
	EnabledTools             []string           `json:"enabled_tools"`
	MaxOutputTokens          int32              `json:"max_output_tokens"`
	InputUsdPerMillion       pgtype.Numeric     `json:"input_usd_per_million"`
	CachedInputUsdPerMillion pgtype.Numeric     `json:"cached_input_usd_per_million"`
	OutputUsdPerMillion      pgtype.Numeric     `json:"output_usd_per_million"`
	Enabled                  bool               `json:"enabled"`
	ValidFrom                pgtype.Timestamptz `json:"valid_from"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	WebSearchUsdPerCall      pgtype.Numeric     `json:"web_search_usd_per_call"`
}

type AppOpenaiWebhookEvent struct {
	WebhookID       string             `json:"webhook_id"`
	EventID         string             `json:"event_id"`
	EventType       string             `json:"event_type"`
	ResponseID      string             `json:"response_id"`
	EventCreatedAt  pgtype.Timestamptz `json:"event_created_at"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	ProcessingError pgtype.Text        `json:"processing_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppOutboxEvent struct {
	ID            int64              `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppOwnerSetting struct {
	UserID               pgtype.UUID        `json:"user_id"`
	QuietHoursStart      pgtype.Time        `json:"quiet_hours_start"`
	QuietHoursEnd        pgtype.Time        `json:"quiet_hours_end"`
	CriticalAlertsBypass bool               `json:"critical_alerts_bypass"`
	MonthlySoftBudgetUsd pgtype.Numeric     `json:"monthly_soft_budget_usd"`
	MonthlyHardBudgetUsd pgtype.Numeric     `json:"monthly_hard_budget_usd"`
	RawRetentionDays     int32              `json:"raw_retention_days"`
	AuditRetentionDays   int32              `json:"audit_retention_days"`
	Version              int64              `json:"version"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AppPromptVersion struct {
	ID              pgtype.UUID        `json:"id"`
	Purpose         string             `json:"purpose"`
	SemanticVersion string             `json:"semantic_version"`
	PromptSha256    []byte             `json:"prompt_sha256"`
	SchemaVersion   string             `json:"schema_version"`
	SchemaSha256    []byte             `json:"schema_sha256"`
	Active          bool               `json:"active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppRawDocument struct {
	ID                pgtype.UUID        `json:"id"`
	SourceID          string             `json:"source_id"`
	CanonicalUrl      string             `json:"canonical_url"`
	ObjectKey         pgtype.Text        `json:"object_key"`
	RawSha256         []byte             `json:"raw_sha256"`
	FirstSeenAt       pgtype.Timestamptz `json:"first_seen_at"`
	FirstFetchedAt    pgtype.Timestamptz `json:"first_fetched_at"`
	SourcePublishedAt pgtype.Timestamptz `json:"source_published_at"`
	ContentPolicy     string             `json:"content_policy"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AppResearchAssertion struct {
	ID              pgtype.UUID        `json:"id"`
	ResearchBriefID pgtype.UUID        `json:"research_brief_id"`
	AssertionIndex  int32              `json:"assertion_index"`
	AssertionText   string             `json:"assertion_text"`
	Material        bool               `json:"material"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppResearchAssertionClaim struct {
	ResearchAssertionID pgtype.UUID        `json:"research_assertion_id"`
	ClaimID             pgtype.UUID        `json:"claim_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AppResearchAssertionSource struct {
	ResearchAssertionID pgtype.UUID        `json:"research_assertion_id"`
	ResearchSourceID    pgtype.UUID        `json:"research_source_id"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type AppResearchBrief struct {
	ID                pgtype.UUID        `json:"id"`
	ClusterID         pgtype.UUID        `json:"cluster_id"`
	AiRunID           pgtype.UUID        `json:"ai_run_id"`
	Headline          string             `json:"headline"`
	Summary           string             `json:"summary"`
	WhyItMatters      string             `json:"why_it_matters"`
	RecommendedAction string             `json:"recommended_action"`
	Confidence        string             `json:"confidence"`
	Uncertainties     []byte             `json:"uncertainties"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AppResearchSource struct {
	ID           pgtype.UUID        `json:"id"`
	AiRunID      pgtype.UUID        `json:"ai_run_id"`
	SourceUrl    string             `json:"source_url"`
	SourceDomain string             `json:"source_domain"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type AppSavedSearch struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Query     string             `json:"query"`
	Filters   []byte             `json:"filters"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AppScheduleDefinition struct {
	ID                     pgtype.UUID        `json:"id"`
	UserID                 pgtype.UUID        `json:"user_id"`
	ScheduleType           string             `json:"schedule_type"`
	Timezone               string             `json:"timezone"`
	LocalTime              pgtype.Time        `json:"local_time"`
	DaysOfWeek             []int16            `json:"days_of_week"`
	Enabled                bool               `json:"enabled"`
	CatchupPolicy          string             `json:"catchup_policy"`
	CatchupGrace           pgtype.Interval    `json:"catchup_grace"`
	NextDueAt              pgtype.Timestamptz `json:"next_due_at"`
	SkipNextAt             pgtype.Timestamptz `json:"skip_next_at"`
	PausedAt               pgtype.Timestamptz `json:"paused_at"`
	Config                 []byte             `json:"config"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	WeekendMode            string             `json:"weekend_mode"`
	MaximumItems           int32              `json:"maximum_items"`
	MinimumScore           pgtype.Numeric     `json:"minimum_score"`
	IncludeComingSoon      bool               `json:"include_coming_soon"`
	IncludeRadarCandidates bool               `json:"include_radar_candidates"`
	IncludeLaterReminders  bool               `json:"include_later_reminders"`
	EmptyBehavior          string             `json:"empty_behavior"`
	Channels               []string           `json:"channels"`
	PausedUntil            pgtype.Timestamptz `json:"paused_until"`
}

type AppScheduleOccurrence struct {
	ID                 pgtype.UUID        `json:"id"`
	ScheduleID         pgtype.UUID        `json:"schedule_id"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	LocalDate          pgtype.Date        `json:"local_date"`
	LocalOffsetSeconds int32              `json:"local_offset_seconds"`
	State              string             `json:"state"`
	TriggerType        string             `json:"trigger_type"`
	IdempotencyKey     string             `json:"idempotency_key"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	Metadata           []byte             `json:"metadata"`
	RiverJobID         pgtype.Int8        `json:"river_job_id"`
}

type AppSearchDocument struct {
	ItemID            pgtype.UUID        `json:"item_id"`
	RevisionID        pgtype.UUID        `json:"revision_id"`
	Title             string             `json:"title"`
	Summary           string             `json:"summary"`
	EntityText        string             `json:"entity_text"`
	PackageName       string             `json:"package_name"`
	NormalizedContent string             `json:"normalized_content"`
	SourceTier        string             `json:"source_tier"`
	LifecycleState    string             `json:"lifecycle_state"`
	PublishedAt       pgtype.Timestamptz `json:"published_at"`
	FirstSeenAt       pgtype.Timestamptz `json:"first_seen_at"`
	SearchVector      interface{}        `json:"search_vector"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AppSource struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	TrustTier       string             `json:"trust_tier"`
	Owner           string             `json:"owner"`
	Origin          string             `json:"origin"`
	ValidationState string             `json:"validation_state"`
	HomepageUrl     string             `json:"homepage_url"`
	ContentPolicy   string             `json:"content_policy"`
	Enabled         bool               `json:"enabled"`
	Topics          []string           `json:"topics"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceCheckpoint struct {
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	Cursor        pgtype.Text        `json:"cursor"`
	Etag          pgtype.Text        `json:"etag"`
	LastModified  pgtype.Text        `json:"last_modified"`
	ProviderState []byte             `json:"provider_state"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceEndpoint struct {
	ID                   pgtype.UUID        `json:"id"`
	RegistryID           string             `json:"registry_id"`
	SourceID             string             `json:"source_id"`
	Connector            string             `json:"connector"`
	Url                  string             `json:"url"`
	PollInterval         pgtype.Interval    `json:"poll_interval"`
	Priority             string             `json:"priority"`
	RobotsPolicy         string             `json:"robots_policy"`
	ExpectedContentTypes []string           `json:"expected_content_types"`
	MaxResponseBytes     int64              `json:"max_response_bytes"`
	FixtureSuite         string             `json:"fixture_suite"`
	Config               []byte             `json:"config"`
	NextPollAt           pgtype.Timestamptz `json:"next_poll_at"`
	LastAttemptAt        pgtype.Timestamptz `json:"last_attempt_at"`
	LastSuccessAt        pgtype.Timestamptz `json:"last_success_at"`
	HealthState          string             `json:"health_state"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceFetch struct {
	ID              int64              `json:"id"`
	EndpointID      pgtype.UUID        `json:"endpoint_id"`
	AttemptedAt     pgtype.Timestamptz `json:"attempted_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Outcome         string             `json:"outcome"`
	StatusCode      pgtype.Int4        `json:"status_code"`
	FinalUrl        pgtype.Text        `json:"final_url"`
	ContentType     pgtype.Text        `json:"content_type"`
	CompressedBytes int64              `json:"compressed_bytes"`
	Bytes           int64              `json:"bytes"`
	DurationMs      int32              `json:"duration_ms"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	RetryAfter      pgtype.Timestamptz `json:"retry_after"`
	Etag            pgtype.Text        `json:"etag"`
	LastModified    pgtype.Text        `json:"last_modified"`
	RawSha256       []byte             `json:"raw_sha256"`
	ObjectKey       pgtype.Text        `json:"object_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppSourceImportPreview struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	DocumentSha256 []byte             `json:"document_sha256"`
	Candidates     []byte             `json:"candidates"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CommittedAt    pgtype.Timestamptz `json:"committed_at"`
}

type AppSourceParseAttempt struct {
	ID            int64              `json:"id"`
	RawDocumentID pgtype.UUID        `json:"raw_document_id"`
	RevisionID    pgtype.UUID        `json:"revision_id"`
	Outcome       string             `json:"outcome"`
	ParserName    string             `json:"parser_name"`
	ParserVersion string             `json:"parser_version"`
	AttemptedAt   pgtype.Timestamptz `json:"attempted_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	DurationMs    int32              `json:"duration_ms"`
	ErrorCode     pgtype.Text        `json:"error_code"`
	Warnings      []byte             `json:"warnings"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppSourceRuntimeOverride struct {
	SourceID       string             `json:"source_id"`
	PollingEnabled bool               `json:"polling_enabled"`
	PollInterval   pgtype.Interval    `json:"poll_interval"`
	Reason         string             `json:"reason"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceValidationRun struct {
	ID               pgtype.UUID        `json:"id"`
	SourceID         string             `json:"source_id"`
	RequestedBy      pgtype.UUID        `json:"requested_by"`
	State            string             `json:"state"`
	CheckCount       int32              `json:"check_count"`
	FailedCheckCount int32              `json:"failed_check_count"`
	Explanation      string             `json:"explanation"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
}

type AppStoryCluster struct {
	ID            pgtype.UUID        `json:"id"`
	PrimaryItemID pgtype.UUID        `json:"primary_item_id"`
	ClusterKey    string             `json:"cluster_key"`
	Title         string             `json:"title"`
	FirstSeenAt   pgtype.Timestamptz `json:"first_seen_at"`
	LastChangedAt pgtype.Timestamptz `json:"last_changed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppTag struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	Name           string             `json:"name"`
	NormalizedName string             `json:"normalized_name"`
	ColorToken     string             `json:"color_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppUser struct {
	ID            pgtype.UUID        `json:"id"`
	GithubUserID  int64              `json:"github_user_id"`
	Login         string             `json:"login"`
	DisplayName   string             `json:"display_name"`
	Timezone      string             `json:"timezone"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Email         string             `json:"email"`
	EmailVerified bool               `json:"email_verified"`
	ImageUrl      pgtype.Text        `json:"image_url"`
}

type AppUserItemState struct {
	UserID              pgtype.UUID        `json:"user_id"`
	ItemID              pgtype.UUID        `json:"item_id"`
	Location            string             `json:"location"`
	IsRead              bool               `json:"is_read"`
	ReadAt              pgtype.Timestamptz `json:"read_at"`
	StarredAt           pgtype.Timestamptz `json:"starred_at"`
	SnoozedUntil        pgtype.Timestamptz `json:"snoozed_until"`
	SnoozedFromLocation pgtype.Text        `json:"snoozed_from_location"`
	ReadingProgress     pgtype.Numeric     `json:"reading_progress"`
	LastParagraphID     pgtype.Text        `json:"last_paragraph_id"`
	LaterPosition       pgtype.Int8        `json:"later_position"`
	DismissedReason     pgtype.Text        `json:"dismissed_reason"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppUserSourcePreference struct {
	UserID              pgtype.UUID        `json:"user_id"`
	SourceID            string             `json:"source_id"`
	Muted               bool               `json:"muted"`
	ExcludeFromDigest   bool               `json:"exclude_from_digest"`
	RelevanceAdjustment pgtype.Numeric     `json:"relevance_adjustment"`
	Version             int64              `json:"version"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type AppVStorySummary struct {
	StoryID           pgtype.UUID        `json:"story_id"`
	ItemID            pgtype.UUID        `json:"item_id"`
	Headline          string             `json:"headline"`
	Summary           string             `json:"summary"`
	WhyItMatters      string             `json:"why_it_matters"`
	RecommendedAction string             `json:"recommended_action"`
	Confidence        string             `json:"confidence"`
	FirstSeenAt       pgtype.Timestamptz `json:"first_seen_at"`
	LastChangedAt     pgtype.Timestamptz `json:"last_changed_at"`
	Status            string             `json:"status"`
	Signal            string             `json:"signal"`
	SourceTier        interface{}        `json:"source_tier"`
	SourceCount       int32              `json:"source_count"`
	ReadTimeMinutes   int32              `json:"read_time_minutes"`
	Uncertainties     []byte             `json:"uncertainties"`
	BriefCreatedAt    pgtype.Timestamptz `json:"brief_created_at"`
	PrimarySourceUrl  string             `json:"primary_source_url"`
}

type AppWatchedTechnology struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Technology        string             `json:"technology"`
	PackageName       string             `json:"package_name"`
	CurrentVersion    string             `json:"current_version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	VersionConstraint string             `json:"version_constraint"`
	Status            string             `json:"status"`
	Source            string             `json:"source"`
	LastVerifiedAt    pgtype.Timestamptz `json:"last_verified_at"`
}
