// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppOutboxEvent struct {
	ID            int64              `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppScheduleDefinition struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ScheduleType  string             `json:"schedule_type"`
	Timezone      string             `json:"timezone"`
	LocalTime     pgtype.Time        `json:"local_time"`
	DaysOfWeek    []int16            `json:"days_of_week"`
	Enabled       bool               `json:"enabled"`
	CatchupPolicy string             `json:"catchup_policy"`
	CatchupGrace  pgtype.Interval    `json:"catchup_grace"`
	NextDueAt     pgtype.Timestamptz `json:"next_due_at"`
	SkipNextAt    pgtype.Timestamptz `json:"skip_next_at"`
	PausedAt      pgtype.Timestamptz `json:"paused_at"`
	Config        []byte             `json:"config"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppScheduleOccurrence struct {
	ID                 pgtype.UUID        `json:"id"`
	ScheduleID         pgtype.UUID        `json:"schedule_id"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	LocalDate          pgtype.Date        `json:"local_date"`
	LocalOffsetSeconds int32              `json:"local_offset_seconds"`
	State              string             `json:"state"`
	TriggerType        string             `json:"trigger_type"`
	IdempotencyKey     string             `json:"idempotency_key"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	Metadata           []byte             `json:"metadata"`
}

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	Login        string             `json:"login"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
