// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppGithubRepository struct {
	SourceID        string             `json:"source_id"`
	NodeID          string             `json:"node_id"`
	RepositoryOwner string             `json:"repository_owner"`
	RepositoryName  string             `json:"repository_name"`
	EnabledEvents   []string           `json:"enabled_events"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AppOutboxEvent struct {
	ID            int64              `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppRawDocument struct {
	ID                pgtype.UUID        `json:"id"`
	SourceID          string             `json:"source_id"`
	CanonicalUrl      string             `json:"canonical_url"`
	ObjectKey         pgtype.Text        `json:"object_key"`
	RawSha256         []byte             `json:"raw_sha256"`
	FirstSeenAt       pgtype.Timestamptz `json:"first_seen_at"`
	FirstFetchedAt    pgtype.Timestamptz `json:"first_fetched_at"`
	SourcePublishedAt pgtype.Timestamptz `json:"source_published_at"`
	ContentPolicy     string             `json:"content_policy"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type AppScheduleDefinition struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	ScheduleType  string             `json:"schedule_type"`
	Timezone      string             `json:"timezone"`
	LocalTime     pgtype.Time        `json:"local_time"`
	DaysOfWeek    []int16            `json:"days_of_week"`
	Enabled       bool               `json:"enabled"`
	CatchupPolicy string             `json:"catchup_policy"`
	CatchupGrace  pgtype.Interval    `json:"catchup_grace"`
	NextDueAt     pgtype.Timestamptz `json:"next_due_at"`
	SkipNextAt    pgtype.Timestamptz `json:"skip_next_at"`
	PausedAt      pgtype.Timestamptz `json:"paused_at"`
	Config        []byte             `json:"config"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppScheduleOccurrence struct {
	ID                 pgtype.UUID        `json:"id"`
	ScheduleID         pgtype.UUID        `json:"schedule_id"`
	ScheduledFor       pgtype.Timestamptz `json:"scheduled_for"`
	LocalDate          pgtype.Date        `json:"local_date"`
	LocalOffsetSeconds int32              `json:"local_offset_seconds"`
	State              string             `json:"state"`
	TriggerType        string             `json:"trigger_type"`
	IdempotencyKey     string             `json:"idempotency_key"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	ErrorCode          pgtype.Text        `json:"error_code"`
	Metadata           []byte             `json:"metadata"`
}

type AppSource struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	TrustTier       string             `json:"trust_tier"`
	Owner           string             `json:"owner"`
	Origin          string             `json:"origin"`
	ValidationState string             `json:"validation_state"`
	HomepageUrl     string             `json:"homepage_url"`
	ContentPolicy   string             `json:"content_policy"`
	Enabled         bool               `json:"enabled"`
	Topics          []string           `json:"topics"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceCheckpoint struct {
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	Cursor        pgtype.Text        `json:"cursor"`
	Etag          pgtype.Text        `json:"etag"`
	LastModified  pgtype.Text        `json:"last_modified"`
	ProviderState []byte             `json:"provider_state"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceEndpoint struct {
	ID                   pgtype.UUID        `json:"id"`
	RegistryID           string             `json:"registry_id"`
	SourceID             string             `json:"source_id"`
	Connector            string             `json:"connector"`
	Url                  string             `json:"url"`
	PollInterval         pgtype.Interval    `json:"poll_interval"`
	Priority             string             `json:"priority"`
	RobotsPolicy         string             `json:"robots_policy"`
	ExpectedContentTypes []string           `json:"expected_content_types"`
	MaxResponseBytes     int64              `json:"max_response_bytes"`
	FixtureSuite         string             `json:"fixture_suite"`
	Config               []byte             `json:"config"`
	NextPollAt           pgtype.Timestamptz `json:"next_poll_at"`
	LastAttemptAt        pgtype.Timestamptz `json:"last_attempt_at"`
	LastSuccessAt        pgtype.Timestamptz `json:"last_success_at"`
	HealthState          string             `json:"health_state"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type AppSourceFetch struct {
	ID              int64              `json:"id"`
	EndpointID      pgtype.UUID        `json:"endpoint_id"`
	AttemptedAt     pgtype.Timestamptz `json:"attempted_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	Outcome         string             `json:"outcome"`
	StatusCode      pgtype.Int4        `json:"status_code"`
	FinalUrl        pgtype.Text        `json:"final_url"`
	ContentType     pgtype.Text        `json:"content_type"`
	CompressedBytes int64              `json:"compressed_bytes"`
	Bytes           int64              `json:"bytes"`
	DurationMs      int32              `json:"duration_ms"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	RetryAfter      pgtype.Timestamptz `json:"retry_after"`
	Etag            pgtype.Text        `json:"etag"`
	LastModified    pgtype.Text        `json:"last_modified"`
	RawSha256       []byte             `json:"raw_sha256"`
	ObjectKey       pgtype.Text        `json:"object_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AppSourceRuntimeOverride struct {
	SourceID       string             `json:"source_id"`
	PollingEnabled bool               `json:"polling_enabled"`
	PollInterval   pgtype.Interval    `json:"poll_interval"`
	Reason         string             `json:"reason"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	Login        string             `json:"login"`
	DisplayName  pgtype.Text        `json:"display_name"`
	Timezone     string             `json:"timezone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
