// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ListDueScheduleIDs(ctx context.Context, arg ListDueScheduleIDsParams) ([]pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
