// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDueScheduleIDs = `-- name: ListDueScheduleIDs :many
select id
from app.schedule_definitions
where enabled
  and paused_at is null
  and next_due_at <= $1
order by next_due_at, id
limit $2
`

type ListDueScheduleIDsParams struct {
	DueAt       pgtype.Timestamptz `json:"due_at"`
	ResultLimit int32              `json:"result_limit"`
}

func (q *Queries) ListDueScheduleIDs(ctx context.Context, arg ListDueScheduleIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listDueScheduleIDs, arg.DueAt, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
